<?php namespace EmailLog\Core\UI\Page;

use EmailLog\Core\DB\TableManager;
use EmailLog\Core\UI\ListTable\LogListTable;

/**
 * Página de listado de registros de correo.
 *
 * @since 2.0
 */
class LogListPage extends BasePage {
	/**
	 * @var LogListTable
	 */
	protected $log_list_table;

	/**
	 * Slug de la página.
	 */
	const PAGE_SLUG = 'email-log';

	/**
	 * Campo de nonce.
	 */
	const LOG_LIST_ACTION_NONCE_FIELD = 'el-log-list-nonce-field';

	/**
	 * Nombre del nonce.
	 */
	const LOG_LIST_ACTION_NONCE = 'el-log-list-nonce';

	/**
	 * Capacidad para gestionar registros de correo.
	 *
	 * @since 2.1.0
	 */
	const CAPABILITY = 'manage_email_logs';

	/**
	 * Configura hooks.
	 */
	public function load() {
		parent::load();

		add_filter( 'set-screen-option', array( $this, 'save_screen_options' ), 10, 3 );

		add_action( 'admin_enqueue_scripts', array( $this, 'load_view_logs_assets' ), 1 );
	}

	/**
	 * Registra la página.
	 *
	 * @inheritdoc
	 */
	public function register_page() {
		add_menu_page(
			__( 'Email Log', 'email-log' ),
			__( 'Email Log', 'email-log' ),
			self::CAPABILITY,
			self::PAGE_SLUG,
			array( $this, 'render_page' ),
			'dashicons-email-alt',
			26
		);

		$this->page = add_submenu_page(
			self::PAGE_SLUG,
			__( 'View Logs', 'email-log'),
			__( 'View Logs', 'email-log'),
			self::CAPABILITY,
			self::PAGE_SLUG,
			array( $this, 'render_page' )
		);

		add_action( "load-{$this->page}", array( $this, 'load_page' ) );

		/**
		 * Se dispara antes de cargar la página de listado de registros.
		 *
		 * @since 2.0
		 *
		 * @param string $page Slug de página.
		 */
		do_action( 'el_load_log_list_page', $this->page );
	}

	/**
	 * Renderiza la página.
	 */
	public function render_page() {
		if ( ! current_user_can( self::CAPABILITY ) ) {
			return;
		}

		add_thickbox();

		$this->log_list_table->prepare_items();
		?>
		<div class="wrap">
			<h2><img class="el-logo" src="<?php echo esc_url(EMAIL_LOG_URL . 'assets/img/logo-64x64.png'); ?>" /><?php esc_html_e( 'Email Log', 'email-log' ); ?></h2>
			<?php settings_errors(); ?>
			<?php
			$export_url = add_query_arg( array(
				'page'          => self::PAGE_SLUG,
				'el_export_csv' => '1',
				'_wpnonce'      => wp_create_nonce( 'el-export-csv' ),
				's'             => isset( $_GET['s'] ) ? sanitize_text_field( $_GET['s'] ) : '',
				'd'             => isset( $_GET['d'] ) ? sanitize_text_field( $_GET['d'] ) : '',
				'd_to'          => isset( $_GET['d_to'] ) ? sanitize_text_field( $_GET['d_to'] ) : '',
				'result'        => isset( $_GET['result'] ) ? sanitize_text_field( $_GET['result'] ) : '',
			), admin_url( 'admin.php' ) );
			?>
			<a href="<?php echo esc_url( $export_url ); ?>" class="button" style="margin-bottom: 10px;">
				<?php esc_html_e( 'Export CSV', 'email-log' ); ?>
			</a>
            <div class="email-log-body-wrapper">
                <form id="email-logs-list" method="get">
                    <input type="hidden" name="page" value="<?php echo esc_attr( self::PAGE_SLUG ); ?>">
                    <?php $this->log_list_table->search_box( __( 'Search Logs', 'email-log' ), 'search_id' ); ?>

                    <?php
                    // Disable the output of referrer hidden field, since it will be generated by the log list table.
                    wp_nonce_field( self::LOG_LIST_ACTION_NONCE, self::LOG_LIST_ACTION_NONCE_FIELD, false );
                    $this->log_list_table->display();
                    ?>
                </form>
            </div>
		</div>
		<?php
		$this->render_page_footer();
	}

	/**
	 * Load page.
	 */
	public function load_page() {
		// Añade opciones de pantalla
		$this->get_screen()->add_option(
			'per_page',
			array(
				'label'   => __( 'Entries per page', 'email-log' ),
				'default' => 20,
				'option'  => 'per_page',
			)
		);

		$this->log_list_table = new LogListTable( $this );
	}

	/**
	 * Obtiene la opción de elementos por página.
	 *
	 * @return int Number of logs a user wanted to be displayed in a page.
	 */
	public function get_per_page() {
		$screen = get_current_screen();
		$option = $screen->get_option( 'per_page', 'option' );

		$per_page = get_user_meta( get_current_user_id(), $option, true );

		if ( empty( $per_page ) || $per_page < 1 ) {
			$per_page = $screen->get_option( 'per_page', 'default' );
		}

		return $per_page;
	}

	/**
	 * Obtiene los argumentos del nonce.
	 *
	 * @return array Nonce args.
	 */
	public function get_nonce_args() {
		return array(
			self::LOG_LIST_ACTION_NONCE_FIELD => wp_create_nonce( self::LOG_LIST_ACTION_NONCE ),
		);
	}

	/**
	 * Obtiene la instancia de TableManager.
	 *
	 * @return TableManager TableManager instance.
	 */
	public function get_table_manager() {
		$email_log = email_log();

		return $email_log->table_manager;
	}

	/**
	 * Guarda opciones de pantalla.
	 *
	 * @since Genesis
	 *
	 * @param bool|int $status Screen option value. Default false to skip.
	 * @param string   $option The option name.
	 * @param int      $value  The number of rows to use.
	 *
	 * @return bool|int
	 */
	public function save_screen_options( $status, $option, $value ) {
		if ( 'per_page' === $option ) {
			return $value;
		} else {
			return $status;
		}
	}

	/**
	 * Carga los recursos en la página de listado.
	 *
	 * @since 2.0.0
	 *
	 * @param string $hook The current admin page.
	 */
	public function load_view_logs_assets( $hook ) {
		if ( 'toplevel_page_email-log' !== $hook && 'email-log_page_email-log-settings' !== $hook ) {
			return;
		}

		$email_log = email_log();
		$version   = $email_log->get_version();

		wp_enqueue_script( 'el-view-logs', EMAIL_LOG_URL . 'assets/js/view-logs.js', array( 'jquery-ui-core', 'jquery-ui-datepicker', 'jquery-ui-tooltip', 'jquery-ui-tabs' ), $version, true );
		wp_enqueue_style( 'el-jquery-ui-css', EMAIL_LOG_URL . 'assets/css/email-log-jquery-ui.min.css', array() );
	}
}
